### PR TITLE
Codeless EventDataConsumer ctor

### LINKED ISSUE #18: UnknownHostException does not log
Warning or Error here?

_Originally posted by @MoonBow-1 in https://github.com/teragrep/aer_02/pull/8#discussion_r1832758745_

### PR DESCRIPTION
**Pull request by eemhu**
fixes #18, #19

### CODE REVIEW

File: src/main/java/com/teragrep/aer_02/metrics/DummyReport.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+ * Licensee must indemnify licensors and authors for any liability that these
+ * contractual assumptions impose on licensors and authors.
+ *
+ * To the extent this program is licensed as part of the Commercial versions of
+ * Teragrep, the applicable Commercial License may apply to this file if you as
+ * a licensee so wish it.
+ */
+package com.teragrep.aer_02.metrics;
+
+public class DummyReport implements Report {
```
Comment (kortemik) [inline src/main/java/com/teragrep/aer_02/metrics/DummyReport.java:48]: this is a Fake, should be under tests?

**Review by kortemik — CHANGES_REQUESTED** [review]

**Review by kortemik — APPROVED** [review]

**Comment by kortemik** [comment]
now it's all good, thank you @eemhu !
